### PR TITLE
Add support for minecraft parkour videos

### PR DESCRIPTION
**Pull request by Abb1x**
The user can now choose their overstimulation method between minecraft parkour and subway surfers videos

### CODE REVIEW

**Comment by Neptune650** [comment]
Now add an option to have both at the same time.

**Comment by Abb1x** [comment]
> Now add an option to have both at the same time.

No. That would result in a dopamine overdose

**Comment by jirkavrba** [comment]
Very cool addition, thanks :heart:

**Comment by jirkavrba** [comment]
I'll make some minor tweaks and release the new version to the VS Code Marketplace.

**Pull request merged**
